# Generated by Django 3.1.1 on 2020-09-04 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DRAMA', 'Drama.'), ('ACTION', 'Action.'), ('COMEDY', 'Comedy.'), ('CRIME', 'Crime.'), ('ADVENTURE', 'Adventure.'), ('FANTASY', 'Fantasy.'), ('SCIENCE FICTION', 'Science Fiction.'), ('SUSPENSE', 'Suspense.'), ('THRILLER', 'Thriller.'), ('HORROR', 'Horror.'), ('ROMANCE', 'Romance.'), ('ANIMATION', 'Animation.'), ('ANIME', 'Anime.'), ('MINI-SERIES', 'Mini-Series.'), ('MYSTERY', 'Mistery.'), ('FAMILY', 'Family.'), ('CHILDREN', 'Chldren.'), ('REALITY', 'Realiy.'), ('DOCUMENTARY', 'Documentary.'), ('SOAP', 'Soap.'), ('HISTORY', 'History.'), ('SPORT', 'Sport.'), ('WESTERN', 'Western.'), ('SPECIAL INTEREST', 'Special Interest.'), ('GAME SHOW', 'Game Show.'), ('TALK SHOW', 'Talk Show.'), ('MARTIAL ARTS', 'Martial Arts.'), ('FOOD', 'Food.'), ('MUSICAL', 'Muscial.'), ('WAR', 'War.'), ('TRAVEL', 'Travel.'), ('NEWS', 'News.'), ('HOME AND GARDEN', 'Home and Garden.'), ('PODCAST', 'Podcast.'), ('INDIE', 'Indie.')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(null=True, to='tv_shows.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_shows.show')),
            ],
        ),
    ]
